apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: kubeseal
    app.kubernetes.io/part-of: kubeseal
    name: sealed-secrets-controller-anyuid
  name: sealed-secrets-controller-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-controller-anyuid
subjects:
- kind: ServiceAccount
  name: sealed-secrets-controller
