---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: kubeseal
    app.kubernetes.io/part-of: kubeseal
    name: sealed-secrets-controller-anyuid
  name: sealed-secrets-controller-anyuid
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
