kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
 - ../htpasswd

patchesJson6902:
  - target:
      group: config.openshift.io
      version: v1
      kind: OAuth
      name: cluster
    path: oauth-ldap-patch.yaml
