---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: tntinfra
  namespace: aap
spec:
  api:
    log_level: DEBUG
    replicas: 1
  image_pull_policy: IfNotPresent
  ingress_type: Route
  no_log: false
  redis_mode: standalone
  route_host: aap.apps.hub.aws.tntinfra.net
  route_tls_termination_mechanism: Edge
  service_type: ClusterIP

  controller:
    disabled: false

  eda:
    disabled: false

  hub:
    disabled: false
    worker:
      replicas: 2

    ## Modify to contain your RWM storage class name
    # storage_type: file
    # file_storage_storage_class: <your-read-write-many-storage-class>
    # file_storage_size: 10Gi
    #
    # storage_type: file
    # file_storage_storage_class: gp3-csi
    # file_storage_size: 10Gi

    ## uncomment if using S3 storage for Content pod
    storage_type: S3
    object_storage_s3_secret: tntinfra-aap-hub-bucket-s3

    ## uncomment if using Azure storage for Content pod
    # storage_type: azure
    # object_storage_azure_secret: azure-secret-name

  lightspeed:
    disabled: true
