---
clustername: &clustername hub
destination: &destination in-cluster

default:
  app:
    enabled: true
    enableAutoSync: false
    autoSyncPrune: false
    project: cluster-config-hub
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/tosmi-gitops/openshift-gitops.git
      targetRevision: HEAD

projects:

  cluster-config-hub:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: cluster-gitops
      # yamllint disable-line rule:line-length
      notifications.argoproj.io/subscribe.on-health-degraded.slack: cluster-gitops
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
      - https://github.com/tosmi-gitops/openshift-gitops
      - https://github.com/redhat-cop/gitops-catalog
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:

  oauth-htpasswd:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
      argocd.argoproj.io/compare-options: IgnoreExtraneous
    destination:
      namespace: default
      name: *destination
    source:
      path: components/configuration/oauth/overlays/htpasswd

  console-customization:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: clusters/hub/configuration/console-customization

  groups:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/configuration/groups/overlays/all

  custom-ca:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: openshift-config
      name: *destination
    source:
      path: components/configuration/custom-ca/base
    ignoreDifferences:
      - group: v1
        kind: ConfigMap
        jsonPointers:
          - /data
          - /metadata

  ingress-default:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: openshift-config
      name: *destination
    source:
      path: clusters/hub/configuration/ingress

  openshift-gitops-config:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/configuration/openshift-gitops/base

  application-gitops:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: application-gitops
      name: *destination
    source:
      path: components/application/application-gitops/overlays/multi-project

  openshift-pipelines:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: openshift-operators
      name: *destination
    source:
      path: components/application/openshift-pipelines/base

  shipwright:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: openshift-operators
      name: *destination
    source:
      path: components/application/shipwright/base
    syncOptions:
      - CreateNamespace=true

  openshift-servicemesh-operator-3.0:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: openshift-operators
      name: *destination
    source:
      path: components/application/openshift-servicemesh/overlays/stable-3.0

  kiali-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: openshift-operators
      name: *destination
    source:
      path: components/application/kiali/base

  openshift-tempo-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: openshift-operators
      name: *destination
    source:
      path: components/application/openshift-tempo-operator/base

  openshift-servicemesh-default:
    annotations:
      # install after
      # - ossm operator
      # - kiali
      argocd.argoproj.io/sync-wave: '8'
    destination:
      namespace: openshift-operators
      name: *destination
    source:
      path: components/configuration/openshift-servicemesh/base


  advanced-cluster-manager:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: open-cluster-management
      name: *destination
    source:
      # yamllint disable-line rule:line-length
      path: components/application/advanced-cluster-management/overlays/release-2.12
    syncOptions:
      - CreateNamespace=true

  multi-cluster-hub:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: open-cluster-management
      name: *destination
    source:
      path: components/application/multi-cluster-hub/base
    syncOptions:
      - CreateNamespace=true

  multi-cluster-observability:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: open-cluster-management
      name: *destination
    source:
      path: components/configuration/multi-cluster-observability/base
    syncOptions:
      - CreateNamespace=true

  ansible-platform-operator-25:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: app
      name: *destination
    source:
      path: components/application/aap/overlays/stable-2.5


  sealed-secrets:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: sealed-secrets
      name: *destination
    source:
      path: components/application/sealed-secrets/base

# event-router:
#   annotations:
#     argocd.argoproj.io/sync-wave: '4'
#   destination:
#     namespace: openshift-logging
#     name: *destination
#   source:
#     path: components/application/event-router/base
#   syncOptions:
#     - CreateNamespace=true

# advanced-cluster-security:
#   annotations:
#     argocd.argoproj.io/sync-wave: '4'
#   destination:
#     namespace: stackrox
#     name: *destination
#   source:
#     path: components/application/advanced-cluster-security/overlays/small
#   syncOptions:
#     - CreateNamespace=true

# falco:
#   annotations:
#     argocd.argoproj.io/sync-wave: '4'
#   destination:
#     namespace: falco
#     name: *destination
#   source:
#     path: components/application/falco/base
#   syncOptions:
#     - CreateNamespace=true
