data_dir: /vector-data-dir
api:
  enabled: true
  address: 127.0.0.1:8686
  playground: true

sources:
  falco:
    type: http_server
    address: 0.0.0.0:8080
    decoding:
      codec: json
    enconding: json

transforms:
  add-clustername:
    type: remap
    inputs:
      - falco
    file: /etc/vector/vrl/remap-add-clustername.vrl

  filter-siem:
    type: filter
    inputs:
      - add-clustername
    condition:
      type: vrl
      file: /etc/vector/vrl/filter-siem.vrl

  filter-audit:
    type: filter
    inputs:
      - add-clustername
    condition:
      type: vrl
      file: /etc/vector/vrl/filter-audit.vrl

  filter-alg:
    type: filter
    inputs:
      - add-clustername
    condition:
      type: vrl
      file: /etc/vector/vrl/filter-alg.vrl

sinks:
  stdout:
    type: console
    encoding:
      codec: json
    inputs:
      - falco

  siem:
    type: kafka
    topic: siem
    bootstrap_servers: "simple-cluster-kafka-tls-0-kafka.apps.sno.aws.tntinfra.net:443"
    buffer:
      when_full: drop_newest
    encoding:
      codec: json
    tls:
      enabled: true
      verify_certificate: false
      verify_hostname: false
      ca_file: /kafka-mitre/ca.crt
      crt_file: /kafka-mitre/user.crt
      key_file: /kafka-mitre/user.key
    inputs:
      - filter-mitre
