---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: falco

helmCharts:
  - name: vector
    version: 0.29.0
    valuesFile: values.yaml
    namespace: falco
    releaseName: vector
    repo: https://helm.vector.dev
    apiVersions:
      - security.openshift.io/v1

configMapGenerator:
  - name: vector-custom-config
    files:
      - vector-custom.yaml=vector-config-cm.yaml
