kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: falco

helmCharts:
- apiVersions:
  - security.openshift.io/v1
  name: vector
  namespace: falco
  releaseName: vector
  repo: https://helm.vector.dev
  valuesFile: values.yaml
  version: 0.29.0

configMapGenerator:
  - name: vector-custom-config
    files:
      - vector-config.yaml=config/vector-config.yaml
      - tests.yaml=config/tests.yaml
  - name: vector-vrl-scripts
    files:
      - vrl/remap-add-clustername.vrl
      - vrl/filter-siem.vrl
      - vrl/filter-audit.vrl
      - vrl/filter-alg.vrl
