---
role: "Aggregator"

extraVolumes:
  - name: kafka-mitre-tls
    secret:
      secretName: kafka-mitre-user-tls

extraVolumeMounts:
  - name: kafka-mitre-tls
    mountPath: /kafka-mitre
    readOnly: true

image:
  repository: timberio/vector
  tag: 0.34.1-debian

containerPorts:
  - containerPort: 8686
    name: api
    protocol: TCP
  - containerPort: 8080
    name: falco
    protocol: TCP
service:
  ports:
  - name: api
    port: 8686
    protocol: TCP
    targetPort: 8686
  - name: falco
    port: 8080
    protocol: TCP
    targetPort: 8080
dataDir: /vector-data-dir
existingConfigMaps:
  - vector-custom-config

# customConfig:
#   data_dir: /vector-data-dir
#   api:
#     enabled: true
#     address: 127.0.0.1:8686
#     playground: true
#   sources:
#     falco:
#       type: http_server
#       address: 0.0.0.0:8080
#       decoding:
#         codec: json
#       enconding: json
#   transforms:
#     add-hostname:
#       type: remap
#       inputs:
#         - falco
#       source: |-
#         hostname, err = get_env_var(hostname)
#         if err != null {
#           hostname = "unknown"
#         }
#         .hostname = hostname
#     filter-mitre:
#       type: filter
#       inputs:
#         - falco
#       condition:
#         type: vrl
#         source: |-
#           includes!(value: .tags, item: "mitre")
#   sinks:
#     stdout:
#       type: console
#       encoding:
#         codec: json
#       inputs:
#         - filter-mitre
#     mitre:
#       type: kafka
#       topic: mitre
#       bootstrap_servers: "simple-cluster-kafka-tls-0-kafka.apps.sno.aws.tntinfra.net:443"
#       buffer:
#         when_full: drop_newest
#       encoding:
#         codec: json
#       tls:
#         enabled: true
#         verify_certificate: false
#         verify_hostname: false
#         ca_file: /kafka-mitre/ca.crt
#         crt_file: /kafka-mitre/user.crt
#         key_file: /kafka-mitre/user.key
#       inputs:
#         - filter-mitre
#   tests:
#     name: Test for add-hostname
#     inputs:
#       insert_at: add-hostname
#       type: log
#     outputs:
#       extract_from: add-hostname
#       conditions:
#         type: vrl
#         source: |-
#           assert_eq!(exists(.hostname), "hostname missing")
