kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base
  - root-cluster-admin.yaml
patches:
  - target:
      group: config.openshift.io
      version: v1
      kind: OAuth
      name: cluster
    path: oauth-htpasswd-patch.yaml

secretGenerator:
  - name: htpasswd-secret
    namespace: openshift-config
    files:
      - htpasswd
    options:
      disableNameSuffixHash: true
      annotations:
        argocd.argoproj.io/sync-options: Prune=false
        argocd.argoproj.io/compare-options: IgnoreExtraneous
