apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sealed-secrets-namespace.yaml
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.4/controller.yaml

# not sure if we need this
# afaik this enables the anyuid scc for the sealed-secrets-controller
# - role-anyuid.yaml
