apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# the default deployment uses kube-system
namespace: sealed-secrets

helmCharts:
  - name: sealed-secrets
    version: 2.17.2
    valuesFile: values.yaml
    namespace: sealed-secrets
    releaseName: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets

resources:
  - sealed-secrets-namespace.yaml
