apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConsoleNotification
      name: cluster-indicator
    patch: |-
      - op: replace
        path: /spec/backgroundColor
        value: '#deac07'
      - op: replace
        path: /spec/color
        value: '#080808'
