apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  - ../../base
  - aws-eu-north-backingstore.yaml
  - aws-eu-west-backingstore.yaml

patches:
  - patch: |-
    - op: add
      path: /spec/pvPoolDefaultStorageClass
      value: gp2

