apiVersion: v2
description: Generic chart for creating series of Argo CD Applications and AppProjects
  following the app-of-apps pattern
kubeVersion: '>=1.14.6'
maintainers:
- name: Gerald Nunn
name: argocd-app-of-app
sources:
- https://github.com/gnunn-gitops/argocd-app-of-app-chart
type: application
version: 0.2.5
