kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: acm-operator-subscription
    patch: |-
      - op: replace
        path: /spec/channel
        value: release-2.12
