---
rhacs:
  central:
    resources:
      requests:
        cpu: '250m'
        memory: '1Gi'
    db:
      resources:
        requests:
          cpu: "250m"
          memory: "1Gi"

  scanner:
    analyzer:
      resources:
        requests:
          cpu: "250m"
          memory: "1Gi"
      autoscaling:
        status: "Disabled"
        max: 1
        min: 1
        replicas: 1
    db:
      resources:
        requests:
          cpu: "250m"
          memory: "1Gi"
