kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: nfs-subdir-provisioner

resources:
  - namespace.yaml

helmCharts:
  - name: nfs-subdir-external-provisioner
    repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    version: 4.0.18
    valuesFile: values.yaml
    namespace: nfs-subdir-provisioner
    releaseName: nfs-subdir-external-provisioner-4.0.18
