kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - tntinfra-apps-cert-sealed-secret.yaml
  - ../../../../components/configuration/ingress/base

patches:
  - target:
      kind: IngressController
      name: default
    patch: |-
      - op: replace
        path: /spec/defaultCertificate/name
        value: tntinfra-cert
