---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: cluster-monitoring-config
    patch:
      - op: add
        path: data/config.yaml
