apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: default
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: #PATCHME#
