---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: mtc-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'release-v1.6'
