---
role: "Aggregator"

env:
  - name: CLUSTERNAME
    valueFrom:
      configMapKeyRef:
        name: vector-variables
        key: CLUSTERNAME
        optional: true

# we need to extra volumes for our config
# - one for mounting kafka secrets (key, cert and CA cert)
# - one for mounting VRL scripts
extraVolumes:
  - name: kafka-mitre-tls
    secret:
      secretName: kafka-mitre-user-tls
  # - name: vrl-scripts
  #   configMap:
  #     name: vector-vrl-scripts
extraVolumeMounts:
  - name: kafka-mitre-tls
    mountPath: /kafka-mitre
    readOnly: true
  # - name: vrl-scripts
  #   mountPath: /etc/vector/vrl
  #   readOnly: true

image:
  repository: timberio/vector
  tag: 0.34.1-debian

containerPorts:
  - containerPort: 8686
    name: api
    protocol: TCP
  - containerPort: 8080
    name: falco
    protocol: TCP
service:
  ports:
  - name: api
    port: 8686
    protocol: TCP
    targetPort: 8686
  - name: falco
    port: 8080
    protocol: TCP
    targetPort: 8080
dataDir: /vector-data-dir
existingConfigMaps:
  - vector-custom-config
