kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: ansible-automation-platform
      namespace: ansible-automation-platform
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable-2.2
