kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base
  # create a simple cluster with one partiation and one user
  - kafka-namespace.yaml
  - simple-cluster.yaml
  - simple-kafkauser.yaml
