kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/path
        value: components/configuration/oauth/overlays/htpasswd
    target:
      kind: Application
      name: config-authentication
