---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-config-managers
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'openshift-gitops'
      name: 'in-cluster'
  sourceRepos:
    - https://github.com/tosmi-gitops/openshift-gitops.git
