apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config-managers
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd-managed: "true"
  template:
    metadata:
      name: 'cluster-config-manager-{{.name}}'
    spec:
      project: cluster-config-managers
      Source:
        repoURL: https://github.com/tosmi-gitops/openshift-gitops.git
        targetRevision: HEAD
        path: clusters/{{.name}}/argocd
      destination:
        name: in-cluster
