apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "bridge-network",
    "type": "cnv-bridge",
    "bridge": "brvirt1",
    "macspoofchk": true
  }'
