apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: brvirt1-policy
spec:
  desiredState:
    interfaces:
      - name: brvirt1
        description: Linux bridge on fractal with enp6s0 as a port
        type: linux-bridge
        state: up
        ipv4:
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: enp6s0
