# yamllint disable rule:line-length
# yamllint disable rule:comments-indentation
---
clustername: &clustername sno-home
destination: &destination in-cluster

default:
  app:
    enabled: true
    enableAutoSync: false
    autoSyncPrune: false
    project: cluster-config-sno-home
    destination:
      namespace: openshift-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/tosmi-gitops/openshift-gitops.git
      targetRevision: HEAD

projects:

  cluster-config-sno-home:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: cluster-gitops
      notifications.argoproj.io/subscribe.on-health-degraded.slack: cluster-gitops
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
      - https://github.com/tosmi-gitops/openshift-gitops
      - https://github.com/redhat-cop/gitops-catalog
    # - https://github.com/gnunn1/gitops-catalog
    # - https://github.com/gnunn-gitops/acm-hub-bootstrap
    # - https://github.com/gnunn1/dev-console-plugin
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:

  openshift-oauth:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
      argocd.argoproj.io/compare-options: IgnoreExtraneous
    destination:
      namespace: default
      name: *destination
    source:
      path: components/configuration/openshift-oauth/overlays/ldap-syno

  sealed-secrets:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: sealed-secrets
      name: *destination
    source:
      path: components/application/sealed-secrets/base

  console-customization:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: clusters/sno-home/configuration/console-customization

  groups:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/configuration/groups/base

  gitops-config:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: clusters/sno-home/configuration/openshift-gitops/

  openshift-pipelines:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/application/openshift-pipelines/base

  openshift-storage:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/configuration/openshift-storage/base

  openshift-nmstate:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/application/openshift-nmstate/base

  virt-network:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: clusters/sno-home/configuration/network/

  apiserver:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/configuration/apiserver/overlays/sno

  nfs-subdir-provisioner:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/application/nfs-subdir-provisioner/base

  metallb:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/application/metallb/base

  metallb-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/configuration/metallb/base

  gateway-api-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/configuration/gateway-api/base

  quay-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/application/redhat-quay-operator/overlays/stable-3.16

  # falco:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '4'
  #   destination:
  #     namespace: falco
  #     name: *destination
  #   source:
  #     path: components/application/falco/base
  #   syncOptions:
  #     - CreateNamespace=true

  # onboarding:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '4'
  #   destination:
  #     namespace: openshift-gitops
  #     name: *destination
  #   source:
  #     path: components/configuration/onboarding/base
