---
kind: Istio
apiVersion: sailoperator.io/v1
metadata:
  name: default
spec:
  namespace: istio-system
  values:
    meshConfig:
      discoverySelectors:
        - matchLabels:
            istio-discovery: enabled
      enableTracing: true
      extensionProviders:
        - name: otel
          opentelemetry:
            port: 4317
            service: otel-collector.istio-system.svc.cluster.local
