---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-monitoring-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: kiali-service-account
    namespace: istio-system
---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali-user-workload-monitoring
  namespace: istio-system
spec:
  external_services:
    prometheus:
      auth:
        type: bearer
        use_kiali_token: true
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    tracing:
      enabled: true
      provider: tempo
      use_grpc: false
      internal_url: https://tempo-simplest-gateway.tempo.svc.cluster.local:8080/api/traces/v1/istio/tempo  # yamllint disable-line rule:line-length
      external_url: https://tempo-simplest-gateway-tempo.apps.hub.aws.tntinfra.net/api/traces/v1/istio/search  # yamllint disable-line rule:line-length
      health_check_url: https://tempo-simplest-gateway-tempo.apps.hub.aws.tntinfra.net/api/traces/v1/north/tempo/api/echo  # yamllint disable-line rule:line-length
      auth:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        insecure_skip_verify: false
        type: bearer
        use_kiali_token: true
      tempo_config:
        url_format: "jaeger"
---
apiVersion: kiali.io/v1alpha1
kind: OSSMConsole
metadata:
  namespace: openshift-operators
  name: ossmconsole
spec:
  version: default
