---
kind: OpenTelemetryCollector
apiVersion: opentelemetry.io/v1beta1
metadata:
  name: otel
  namespace: istio-system
spec:
  observability:
    metrics: {}
  deploymentUpdateStrategy: {}
  config:
    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    exporters:
      debug:
        verbosity: detailed
      otlp/istio:
        endpoint: tempo-simplest-gateway.tempo.svc.cluster.local:8090
        tls:
          # insecure: false
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"  # yamllint disable rule:line-length

        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: "istio"
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: '0.0.0.0:4317'
          http: {}
    service:
      extensions:
        - bearertokenauth
      pipelines:
        traces:
          exporters:
            - otlp/istio
            - debug
          receivers:
            - otlp
