---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: argocd-app-of-app
    version: 0.2.5
    valuesFile: values.yaml
    namespace: openshift-gitops
    releaseName: argocd-app-of-app-0.2.5
