---
clustername: &clustername app
destination: &destination app

default:
  app:
    enabled: true
    enableAutoSync: false
    autoSyncPrune: false
    project: cluster-config-app
    destination:
      namespace: openshift-gitops
      server: https://api.app.aws.tntinfra.net:6443
    source:
      repoURL: https://github.com/tosmi-gitops/openshift-gitops.git
      targetRevision: HEAD

projects:

  cluster-config-app:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: cluster-gitops
      notifications.argoproj.io/subscribe.on-health-degraded.slack: cluster-gitops
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
      - https://github.com/tosmi-gitops/openshift-gitops
      - https://github.com/redhat-cop/gitops-catalog
    # - https://github.com/gnunn1/gitops-catalog
    # - https://github.com/gnunn-gitops/acm-hub-bootstrap
    # - https://github.com/gnunn1/dev-console-plugin
    destinations: |
      - namespace: '*'
        server: https://api.app.aws.tntinfra.net:6443
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:

  oauth-htpasswd:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
      argocd.argoproj.io/compare-options: IgnoreExtraneous
    destination:
      namespace: default
      name: *destination
    source:
      path: components/configuration/oauth/overlays/htpasswd

  console-customization:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: clusters/app/configuration/console-customization

  groups:
    annotations:
      argocd.argoproj.io/sync-wave: '4'
    destination:
      namespace: default
      name: *destination
    source:
      path: components/configuration/groups/overlays/all

  # event-router:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '4'
  #   destination:
  #     namespace: openshift-logging
  #     name: *destination
  #   source:
  #     path: components/apps/event-router/base
  #   syncOptions:
  #     - CreateNamespace=true

  # falco:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '4'
  #   destination:
  #     namespace: falco
  #     name: *destination
  #   source:
  #     path: components/apps/falco/base
  #   syncOptions:
  #     - CreateNamespace=true
