---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: tntinfra
  namespace: aap
spec:
  eda:
    disabled: false
  route_tls_termination_mechanism: Edge
  service_type: ClusterIP
  ingress_type: Route
  no_log: false
  redis_mode: standalone
  image_pull_policy: IfNotPresent
  lightspeed:
    disabled: true
  hub:
    disabled: false
    object_storage_s3_secret: tntinfra-aap-hub-bucket-s3
    storage_type: S3
    worker:
      replicas: 2
  api:
    log_level: DEBUG
    replicas: 1
  controller:
    disabled: false
  route_host: aap.apps.hub.aws.tntinfra.net
