kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: #subscription-name#
    patch: |-
      - op: replace
        path: /metadata/name
        value: servicemeshoperator3
      - op: replace
        path: /spec/name
        value: servicemeshoperator3
      - op: replace
        path: /spec/channel
        value: stable-3.0
