apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: ctrl
  namespace: ansible-automation-platform
spec:
  # see https://github.com/ansible/awx-operator
  # for more info about support configuration
  # options
  service_type: ClusterIP
  ingress_type: route
  route_host: ctrl.apps.ocp.lan.stderr.at
  create_preload_data: true
  route_tls_termination_mechanism: Edge
  postgres_storage_requirements:
    requests:
      storage: "8Gi"
  postgres_storage_class: ceph-block
  garbage_collect_secrets: false
  # loadbalancer_port: 80
  # loadbalancer_protocol: http
  # nodeport_port: 30080
  image_pull_policy: IfNotPresent
  projects_storage_size: 5Gi
  task_privileged: false
  projects_storage_access_mode: ReadWriteMany
  projects_persistence: false
  replicas: 1
  admin_user: admin
