---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: falco

helmCharts:
  - name: falco
    version: 3.8.0
    valuesFile: values.yaml
    namespace: openshift-gitops
    releaseName: falco
    repo: https://falcosecurity.github.io/charts

resources:
  - namespace.yaml
