---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: falco

helmCharts:
  - name: falco
    version: 3.8.0
    valuesFile: values.yaml
    namespace: falco
    releaseName: falco
    repo: https://falcosecurity.github.io/charts
    apiVersions:
      - security.openshift.io/v1

resources:
  - namespace.yaml
  - falcosidekick-any-uid-scc.yaml
  - master-machineconfig.yaml
  - worker-machineconfig.yaml
