driver:
  kind: ebpf
  loader:
    initContainer:
      image:
        repository: falcosecurity/falco-driver-loader-legacy
        #registry: docker.io
        # repository: tosmi/falco-driver-loader
        #tag: 0.36.1

falco:
  json_output: true
  json_include_output_property: true
  log_syslog: false
  log_level: info

falcosidekick:
  enabled: true
  webui:
    enabled: true

customRules:
  rules-tty-commands.yaml: |-
    - rule: Log commands in an interactive shell
      desc: >-
        Log all commands executed in an container that has a tty attached. Taken from
        https://github.com/falcosecurity/falco/issues/2338#issuecomment-1631308628.
      condition: >-
        spawned_process
        and container
        and proc.tty != 0
        and proc.is_vpgid_leader=true
      output: Executed command in container (proc_exe=%proc.exe proc_sname=%proc.sname gparent=%proc.aname[2] proc_exe_ino_ctime=%proc.exe_ino.ctime proc_exe_ino_mtime=%proc.exe_ino.mtime proc_exe_ino_ctime_duration_proc_start=%proc.exe_ino.ctime_duration_proc_start proc_cwd=%proc.cwd container_start_ts=%container.start_ts evt_type=%evt.type user=%user.name user_uid=%user.uid user_loginuid=%user.loginuid process=%proc.name proc_exepath=%proc.exepath parent=%proc.pname command=%proc.cmdline terminal=%proc.tty exe_flags=%evt.arg.flags %container.info)
      priority: CRITICAL
      tags: [custom_rule, container, process, tty]
