---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: opentelemetry-product
  namespace: openshift-opentelemetry-operator
spec:
  channel: stable
  installPlanApproval: Manual
  name: opentelemetry-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
