---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
 - ../htpasswd
 - ldap-secret.yaml
 - ldap-ca-cert-configmap.yaml

patches:
  - target:
      group: config.openshift.io
      version: v1
      kind: OAuth
      name: cluster
    path: oauth-ldap-patch.yaml
