---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ldap-secret
  namespace: openshift-config
spec:
  encryptedData:
    bindPassword: AgBkkhZXEXmql+duOuyIyOwfzBw4GdFgxerFeosed0r6nOP5y2ZBJuSO5UzsSG2sxI/bQ6raiiekq8n1UoB+IgKx/WpZVDbr4B4bxEL5ezg0DZksASbRMZKOKfrxdK/DlxGPKO4rHiFmyXLQ0X3r46WKrdt25d78u1pJoUsGRlPRzOvZl8LA5TX4reYu7Zctlh1Q9QV1+Zf+lD/4V7QxeudhMsUUEnQKs49SYSSr3sG5n6xCr3sDwjEF8eVSqkCBM9WCrSfQEXKaE5a8UGw6oulircLz531NMAyXTtQIwmeDGe4MboQ0T5G4S9IRNi7P++SsQtbwgHxNhAnt7EtvUhAToJ/H2IzzyVroIAn3lpOUdgRoESYG470GNhAJomgfiq1iPg6AWaT7jqRXuzbWjOKCBsfmSbvq3znfK5VP9fEMaPNqdSkOObHiBKuEiIHNGTFPdIGaRBNQNrt+so1IRvOvWRzLEJ4AJ3Y8zCBFgfeyllRDggQjG8dyTEoPhCxtG0JLeizK5ZoHKhy4KNQAn0FyH+OH4IEa2dBkM97regYdPXvMPshfINj3pC3CBe6cqUuHWEhGS3FDJmSxpiH89IFhC+0ZjMq6vifSDsEbxPqhwFmPfHhcTo0ZLGo4jFon6HUX8hDvR+tIupOQOoVnSlrhvCSkHhAqMvbWkhTf8o6ZmyyzAzN9eNjTzfRVrW6g8sVQQgTy6rw5T/lWZ1TMpSn+8io=
  template:
    metadata:
      name: ldap-secret
      namespace: openshift-config
